openapi: 3.0.1
info:
  title: Finance manager API
  description: OpenAPI schema of budget application
  version: 1.0.0

paths:

  /api/users/{userId}:

    delete:
      security:
        - bearerAuth: []
      summary: All user data is deleted (wallets and transactions). User entity is NOT deleted from database
      tags:
        - Delete User Data
      operationId: deleteUserDataById
      parameters:
        - name: userId
          in: path
          required: true
          description: User ID
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Your account is successfully deleted'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/users/{userId}/logout:

    get:
      security:
        - bearerAuth: []
      summary: User logout with JWT Auth de-activation
      tags:
        - User Logout
      operationId: logoutUserById
      parameters:
        - name: userId
          in: path
          required: true
          description: User ID
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Logout is successful'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/users/{userId}/settings:

    get:
      security:
        - bearerAuth: []
      summary: List of the personal User settings
      tags:
        - User Settings
      operationId: userSettingsByUserId
      parameters:
        - name: userId
          in: path
          required: true
          description: User ID
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SettingsDto"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          example: 4XX
        message:
          type: string
          example: 'text describing the error'

    SettingsDto:
      type: object
      required:
        - language
        - ui_theme
      properties:
        language:
          type: string
          example: 'English'
        message:
          type: boolean
          example: 'Dark UI theme'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
