openapi: 3.0.0
info:
  title: API for Exadel budget application
  description: OpenAPI schema of budget application
  version: 1.0.0
tags:
  - name: User Management
paths:
  /users/login:
    post:
      summary: LogIn
      description: As a User I want to to have a login functionality so that I can get an access to my User account
      tags:
        - User Management
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginDto'
        description: DTO for User entity
        required: true
      responses:
        '200':
          description: OK
          headers:
            Authorization:
              schema:
                type: string
                example: Bearer 123
              description: JWT Authorization header using the Bearer scheme
        '401':
          description: Invalid Email or Password
          content:
            application/json:
              schema:
                type: string
                example: Invalid Email or Password
      security: []
components:
  schemas:
    UserLoginDto:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
      x-examples:
        example-1:
          username: user@exadel.com
          password: User
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: JWT Authorization header using the Bearer scheme
security:
  - bearerAuth: []
